name: Build

on:
  push:
    branches:
      - main

jobs:
  ddb:
    runs-on: ubuntu-latest

    steps:
      - uses: TykTechnologies/go-plugin-compiler-action@main
        with:
          gw_tag: v3.1.1
          plugin_name: basicauth-ddb.so
